### PR TITLE
New clustering methods

### PR DESCRIPTION
**Pull request by CameronGBell**
Adds clustering methods for individual and series of images, using a number of filter kernels selectable using the list of dictionaries `parameters`

### CODE REVIEW

**Comment by CameronGBell** [comment]
I'll probably add some more tests before merging, for each of the new functions I've added

**Comment by CameronGBell** [comment]
I'll add some test for the 2 new functions before the merge,  to increase the code coverage

**Comment by TomSlater** [comment]
Looks good in general. It shouldn't be difficult to add in a mask for conversion to supervised learning too (i.e. when you've drawn on the image).

The parameter input is maybe a little difficult to change, but probably isn't an issue.

Once you add tests and documentation I'll test it out properly.

**Comment by TomSlater** [comment]
Is there anything in this PR that isn't in #60 ? I can't see anything but I just though I'd check. If not, I'll just check and merge #60 .

**Pull request merged**
